;;;;;;;;;;;;;;;;;
;; ASCII Lexer ;;
;;;;;;;;;;;;;;;;;

;; Visible characters
; The excluded characters are either below in ascii-nl or ascii-space, or are
; control charactres.
ascii-visible = %x21-7E

;; Whitespace
ascii-nl = %x0A-0D
ascii-space = %x09 / %x20

;; Letters
ascii-lower = %x61-7A
ascii-upper = %x41-5A
ascii-alpha = ascii-lower / ascii-upper

;; Numbers
ascii-digit = %x30-39
