Document: smudge
Title: Debian smudge Manual
Author: <insert document author here>
Abstract: This manual describes what smudge is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/smudge/smudge.sgml.gz

Format: postscript
Files: /usr/share/doc/smudge/smudge.ps.gz

Format: text
Files: /usr/share/doc/smudge/smudge.text.gz

Format: HTML
Index: /usr/share/doc/smudge/html/index.html
Files: /usr/share/doc/smudge/html/*.html
